# Generated by Django 5.1.5 on 2025-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUploadSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='my_file',
            field=models.BinaryField(),
        ),
    ]
